language: java
sudo: false
script: mvn clean install
before_install:
  - chmod -R +x .utility
after_success:
  - .utility/push-javadoc-to-gh-pages.sh
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Dmaven.javadoc.skip=true"
  skip_cleanup: true